Name:           ros-indigo-concert-service-utilities
Version:        0.6.0
Release:        0%{?dist}
Summary:        ROS concert_service_utilities package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/concert_service_utilities
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-rocon-icons
Requires:       ros-indigo-rocon-python-comms
Requires:       ros-indigo-rospy
Requires:       ros-indigo-rosunit
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rostest

%description
Utilities for services.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Aug 25 2014 Daniel Stonier <d.stonier@gmail.com> - 0.6.0-0
- Autogenerated by Bloom

